services:
  cli:
    build: .
    container_name: cli
    depends_on:
      postgres:
        condition: service_healthy
    env_file: .env
    profiles: ["cli"]
    volumes:
      - .:/sources
      - type: bind
        source: ${GO_REPLAYS}
        target: ${GO_REPLAYS}
        read_only: true

  postgres:
    container_name: postgres
    env_file: .env
    healthcheck:
      interval: 5s
      retries: 10
      test: ["CMD-SHELL", "pg_isready -U postgres -d starcraft2"]
      timeout: 5s
    image: postgres:18.4
    volumes:
      - ./postgres:/var/lib/postgresql
      - ./sqlc/schema.sql:/docker-entrypoint-initdb.d/schema.sql:ro

  ui:
    build: .
    command: ["-action", "serve"]
    container_name: ui
    depends_on:
      postgres:
        condition: service_healthy
    env_file: .env
    ports:
      - "127.0.0.1:${GO_PORT}:${GO_PORT}"
    volumes:
      - .:/sources
