server {
    listen      [::]:80;
    listen      80;
    return      301 https://starcraft2.mahendrakalkura.com$request_uri;
    server_name starcraft2.mahendrakalkura.com;
}

server {
    include             /etc/letsencrypt/options-ssl-nginx.conf;
    listen              [::]:443 ssl;
    listen              443 ssl;
    root                /opt/starcraft2;
    server_name         starcraft2.mahendrakalkura.com;
    ssl                 on;
    ssl_certificate     /etc/letsencrypt/live/starcraft2.mahendrakalkura.com/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/starcraft2.mahendrakalkura.com/privkey.pem;
    ssl_dhparam         /etc/letsencrypt/ssl-dhparams.pem;
    location / {
        proxy_pass         http://0.0.0.0:8080;
        proxy_read_timeout 300s;
        proxy_redirect     off;
        proxy_set_header   Host $host;
        proxy_set_header   X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header   X-Forwarded-Host $server_name;
        proxy_set_header   X-Forwarded-Proto $scheme;
        proxy_set_header   X-Real-IP $remote_addr;
    }
}
